# Generated by Django 2.2 on 2019-07-02 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='joblist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=500)),
                ('issu_date', models.CharField(max_length=50)),
                ('company_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=100)),
                ('no_of_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postAjob.joblist')),
            ],
        ),
    ]
